# Generated by Django 3.1.2 on 2020-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('identity_number', models.CharField(blank=True, max_length=50)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
