# Generated by Django 3.1.2 on 2020-10-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='date_registered',
        ),
    ]
