# Generated by Django 3.1.2 on 2020-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_voter_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('image', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='TallyingAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('private_key', models.CharField(blank=True, max_length=2500)),
                ('public_key', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='private_key',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='voter',
            name='public_key',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
