# Generated by Django 3.1.2 on 2020-10-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201022_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Candidate',
        ),
        migrations.AddField(
            model_name='tallyingauthority',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
