# Generated by Django 3.1.2 on 2020-10-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201024_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, max_length=2500)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.voter')),
            ],
        ),
    ]
