# Generated by Django 3.1.2 on 2020-10-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='a_reference',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='voter',
            name='b_reference',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
    ]
