# Generated by Django 3.1.2 on 2020-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201025_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyingauthority',
            name='x_value',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='tallyingauthority',
            name='y_value',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
