# Generated by Django 3.1.2 on 2020-11-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201025_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
