# Generated by Django 3.1.2 on 2020-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201105_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='xnt',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ynt',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
